
export const IPL_PLAYERS = [
  { name: "Virat Kohli", team: "RCB", role: "Batsman", nationality: "Indian", style: "Right Hand", hand: "Right", matches: 200, active: true, captain: true },
  { name: "MS Dhoni", team: "CSK", role: "Wicketkeeper", nationality: "Indian", style: "Right Hand", hand: "Right", matches: 200, active: true, captain: true },
  { name: "Rohit Sharma", team: "MI", role: "Batsman", nationality: "Indian", style: "Right Hand", hand: "Right", matches: 200, active: true, captain: true },
  { name: "Hardik Pandya", team: "MI", role: "All-rounder", nationality: "Indian", style: "Right Hand", hand: "Right", matches: 100, active: true, captain: true },
  { name: "Rashid Khan", team: "GT", role: "Bowler", nationality: "Overseas", style: "Spin", hand: "Right", matches: 100, active: true, captain: false },
  { name: "AB de Villiers", team: "RCB", role: "Batsman", nationality: "Overseas", style: "Right Hand", hand: "Right", matches: 150, active: false, captain: false },
  { name: "Chris Gayle", team: "PBKS", role: "Batsman", nationality: "Overseas", style: "Left Hand", hand: "Left", matches: 140, active: false, captain: false },
  { name: "Sunil Narine", team: "KKR", role: "All-rounder", nationality: "Overseas", style: "Spin", hand: "Left", matches: 150, active: true, captain: false },
  { name: "Jasprit Bumrah", team: "MI", role: "Bowler", nationality: "Indian", style: "Fast", hand: "Right", matches: 120, active: true, captain: false },
  { name: "Shubman Gill", team: "GT", role: "Batsman", nationality: "Indian", style: "Right Hand", hand: "Right", matches: 90, active: true, captain: true },
  { name: "Andre Russell", team: "KKR", role: "All-rounder", nationality: "Overseas", style: "Fast", hand: "Right", matches: 110, active: true, captain: false },
  { name: "KL Rahul", team: "LSG", role: "Wicketkeeper", nationality: "Indian", style: "Right Hand", hand: "Right", matches: 100, active: true, captain: true },
  { name: "Suresh Raina", team: "CSK", role: "Batsman", nationality: "Indian", style: "Left Hand", hand: "Left", matches: 200, active: false, captain: false },
  { name: "Lasith Malinga", team: "MI", role: "Bowler", nationality: "Overseas", style: "Fast", hand: "Right", matches: 120, active: false, captain: false },
  { name: "Gautam Gambhir", team: "KKR", role: "Batsman", nationality: "Indian", style: "Left Hand", hand: "Left", matches: 150, active: false, captain: true },
  { name: "David Warner", team: "DC", role: "Batsman", nationality: "Overseas", style: "Left Hand", hand: "Left", matches: 170, active: true, captain: true },
  { name: "Ravindra Jadeja", team: "CSK", role: "All-rounder", nationality: "Indian", style: "Spin", hand: "Left", matches: 200, active: true, captain: false },
  { name: "Jos Buttler", team: "RR", role: "Wicketkeeper", nationality: "Overseas", style: "Right Hand", hand: "Right", matches: 90, active: true, captain: false },
  { name: "Yuzvendra Chahal", team: "RR", role: "Bowler", nationality: "Indian", style: "Spin", hand: "Right", matches: 140, active: true, captain: false },
  { name: "Suryakumar Yadav", team: "MI", role: "Batsman", nationality: "Indian", style: "Right Hand", hand: "Right", matches: 130, active: true, captain: false },
  { name: "Glenn Maxwell", team: "RCB", role: "All-rounder", nationality: "Overseas", style: "Spin", hand: "Right", matches: 120, active: true, captain: false },
  { name: "Faf du Plessis", team: "RCB", role: "Batsman", nationality: "Overseas", style: "Right Hand", hand: "Right", matches: 130, active: true, captain: true },
  { name: "Sanju Samson", team: "RR", role: "Wicketkeeper", nationality: "Indian", style: "Right Hand", hand: "Right", matches: 150, active: true, captain: true },
  { name: "Pat Cummins", team: "SRH", role: "Bowler", nationality: "Overseas", style: "Fast", hand: "Right", matches: 50, active: true, captain: true },
  { name: "Kieron Pollard", team: "MI", role: "All-rounder", nationality: "Overseas", style: "Medium", hand: "Right", matches: 180, active: false, captain: false },
  { name: "Shane Watson", team: "CSK", role: "All-rounder", nationality: "Overseas", style: "Medium", hand: "Right", matches: 140, active: false, captain: false },
  { name: "Adam Gilchrist", team: "PBKS", role: "Wicketkeeper", nationality: "Overseas", style: "Left Hand", hand: "Left", matches: 80, active: false, captain: true },
  { name: "Brendon McCullum", team: "KKR", role: "Batsman", nationality: "Overseas", style: "Right Hand", hand: "Right", matches: 100, active: false, captain: false },
  { name: "Quinton de Kock", team: "LSG", role: "Wicketkeeper", nationality: "Overseas", style: "Left Hand", hand: "Left", matches: 90, active: true, captain: false },
  { name: "Rishabh Pant", team: "DC", role: "Wicketkeeper", nationality: "Indian", style: "Left Hand", hand: "Left", matches: 100, active: true, captain: true }
];

export const ATTRIBUTE_QUESTIONS = [
  { key: "nationality", value: "Indian", question: "Is the player an Indian national?" },
  { key: "role", value: "Batsman", question: "Is the player a specialist batsman?" },
  { key: "role", value: "Bowler", question: "Is the player a specialist bowler?" },
  { key: "role", value: "All-rounder", question: "Is the player an all-rounder?" },
  { key: "role", value: "Wicketkeeper", question: "Is the player a wicketkeeper?" },
  { key: "style", value: "Spin", question: "Is the player a spin bowler?" },
  { key: "style", value: "Fast", question: "Is the player a fast/medium-fast bowler?" },
  { key: "hand", value: "Left", question: "Is the player a left-handed player (batting/bowling)?" },
  { key: "active", value: "true", question: "Is the player currently active in the IPL (2024 season)?" },
  { key: "captain", value: "true", question: "Has the player ever captained an IPL side?" },
  { key: "team", value: "CSK", question: "Has the player ever played for Chennai Super Kings (CSK)?" },
  { key: "team", value: "MI", question: "Has the player ever played for Mumbai Indians (MI)?" },
  { key: "team", value: "RCB", question: "Has the player ever played for Royal Challengers Bengaluru (RCB)?" },
  { key: "team", value: "KKR", question: "Has the player ever played for Kolkata Knight Riders (KKR)?" },
  { key: "team", value: "SRH", question: "Has the player ever played for Sunrisers Hyderabad (SRH)?" },
];
